
cmp start_batch

project start_batch

project start_batch mc8051_top
cmp add_assignment "" "" "" ROOT "|mc8051_top"
cmp add_assignment "" "" "" FAMILY "CYCLONE"
cmp add_assignment "mc8051_top" "" "" DEVICE "EP1C20F400C7"
project add_assignment "" "mc8051_top" "" "" "EDA_DESIGN_ENTRY_SYNTHESIS_TOOL" "SYNPLIFY"
project add_assignment "" "eda_design_synthesis" "" "" "EDA_USE_LMF" "synplcty.lmf"
project add_assignment "" "|cyclonepll:i_cyclonepll|s_clk_pll_setting" "" "" "DUTY_CYCLE" "50"
project add_assignment "mc8051_top" "" "" "|cyclonepll:i_cyclonepll|s_clk_pll" "GLOBAL_SIGNAL" "ON"
project add_assignment "mc8051_top" "" "" "|cyclonepll:i_cyclonepll|s_clk_pll" "USE_CLOCK_SETTINGS" "|cyclonepll:i_cyclonepll|s_clk_pll_setting"
project add_assignment "" "|cyclonepll:i_cyclonepll|s_clk_pll_setting" "" "" "FMAX_REQUIREMENT" "18.8MHZ"
project add_assignment "" "clk_setting" "" "" "DUTY_CYCLE" "50"
project add_assignment "mc8051_top" "" "" "clk" "GLOBAL_SIGNAL" "ON"
project add_assignment "mc8051_top" "" "" "clk" "USE_CLOCK_SETTINGS" "clk_setting"
project add_assignment "" "clk_setting" "" "" "FMAX_REQUIREMENT" "60.0MHZ"
project add_assignment "" "" "" "" "TAO_FILE" "myresults.tao"
project add_assignment "" "" "" "" "SOURCES_PER_DESTINATION_INCLUDE_COUNT" "1000"
project add_assignment "" "" "" "" "ROUTER_REGISTER_DUPLICATION" "ON"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_o\[0\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_o\[1\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_o\[2\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_o\[3\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_o\[4\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_o\[5\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_o\[6\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_o\[7\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_o\[0\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_o\[1\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_o\[2\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_o\[3\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_o\[4\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_o\[5\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_o\[6\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_o\[7\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_o\[0\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_o\[1\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_o\[2\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_o\[3\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_o\[4\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_o\[5\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_o\[6\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_o\[7\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_o\[0\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_o\[1\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_o\[2\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_o\[3\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_o\[4\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_o\[5\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_o\[6\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_o\[7\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "all_rxd_o\[0\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "all_txd_o\[0\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "all_rxdwr_o\[0\]"  "TCO_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "int0_i\[0\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "int1_i\[0\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "all_t0_i\[0\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "all_t1_i\[0\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "all_rxd_i\[0\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_i\[0\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_i\[1\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_i\[2\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_i\[3\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_i\[4\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_i\[5\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_i\[6\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p0_i\[7\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_i\[0\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_i\[1\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_i\[2\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_i\[3\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_i\[4\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_i\[5\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_i\[6\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p1_i\[7\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_i\[0\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_i\[1\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_i\[2\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_i\[3\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_i\[4\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_i\[5\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_i\[6\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p2_i\[7\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_i\[0\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_i\[1\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_i\[2\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_i\[3\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_i\[4\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_i\[5\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_i\[6\]"  "TSU_REQUIREMENT"  "53.333ns"
project add_assignment "mc8051_top" "" "|cyclonepll:i_cyclonepll|s_clk_pll"  "p3_i\[7\]"  "TSU_REQUIREMENT"  "53.333ns"

# False path constraints 

# Multicycle constraints 

# Path delay constraints 

project end_batch mc8051_top

project end_batch

cmp end_batch
